version: "2.0"

services:
  sub_service:
    build: .
    image: infosub:latest
    links:
      - sub_db:db
    restart: always
    ports:
      - 80:5000
    environment:
      - DATABASE_USER=root
      - DATABASE_PASS=j79x4txHRz6sAm73
      - DATABASE_URI=db
      - DATABASE_DB=info
      - SECRET_KEY=3LU23tFm2yvy6D4x
      - RUNTIME=PRODUCTION


  sub_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=j79x4txHRz6sAm73
      - MYSQL_DATABASE=info
    restart: always

